version: "3.3"
services:
  minio:
    image: minio/minio
    command: "server --address 0.0.0.0:9000 /data"
    environment:
      MINIO_ACCESS_KEY: mwdb
      MINIO_SECRET_KEY: mwdbmwdb
    ports:
      - "127.0.0.1:8090:9000"
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: mwdb
      POSTGRES_DB: mwdb
      POSTGRES_PASSWORD: mwdbsecretpass
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:8379:6379"
  mwdb:
    build:
      context: .
      dockerfile: docker/Dockerfile-mwdb
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./config/karton.ini:/etc/karton/karton.ini
      - ./config/mwdb.ini:/app/mwdb.ini
    environment:
      MWDB_REDIS_URI: "redis://redis/"
      MWDB_POSTGRES_URI: "postgresql://mwdb:mwdbsecretpass@postgres/mwdb"
      MWDB_ADMIN_PASSWORD: "admin"
      UWSGI_PROCESSES: 4
    ports:
      - "127.0.0.1:8080:8080"
  karton-system:
    image: certpl/karton-system:0af047e3026915ef42890f772d129886d2e6305b
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --setup-bucket
  karton-classifier:
    image: certpl/karton-classifier:a40fea7a130890fec76c5b444445bee67c83921c
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.ini:/etc/karton/karton.ini
  karton-dashboard:
    image: certpl/karton-dashboard:78f6ac8f1dcb0fdbc194ea8fbbfc46c1575686f6
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.ini:/etc/karton/karton.ini
    ports:
      - "127.0.0.1:8030:5000"
  karton-mwdb-reporter:
    image: certpl/karton-mwdb-reporter:b8dc658b2f5489f7d9776970e6cd5fcca3ff0503
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.ini:/etc/karton/karton.ini
