version: "3.3"
services:
  minio:
    image: minio/minio
    command: "server --address 0.0.0.0:9000 /data"
    environment:
      MINIO_ACCESS_KEY: mwdb
      MINIO_SECRET_KEY: mwdbmwdb
    ports:
      - "127.0.0.1:8090:9000"
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: mwdb
      POSTGRES_DB: mwdb
      POSTGRES_PASSWORD: mwdbsecretpass
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:8379:6379"
  mwdb:
    build:
      context: .
      dockerfile: docker/Dockerfile-mwdb
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
      - ./config/mwdb.ini:/app/mwdb.ini
    environment:
      MWDB_REDIS_URI: "redis://redis/"
      MWDB_POSTGRES_URI: "postgresql://mwdb:mwdbsecretpass@postgres/mwdb"
      MWDB_ADMIN_PASSWORD: "admin"
      UWSGI_PROCESSES: 4
    ports:
      - "127.0.0.1:8080:8080"
  karton-system:
    image: certpl/karton-system:158d07960d8cd39dee8771af719f560df93b3212
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --setup-bucket
  karton-classifier:
    image: certpl/karton-classifier:320c99de8e05ff3d029609e73ac31bcf2d0ba56c
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
  karton-dashboard:
    image: certpl/karton-dashboard:2c35fb3cae399dba8913f8ad1be9dd6b820b1fd6
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    ports:
      - "127.0.0.1:8030:5000"
  karton-mwdb-reporter:
    image: certpl/karton-mwdb-reporter:a4a5a2ece14073e3a25a38bd5f1b0fa14ba725d3
    depends_on:
      - redis
      - minio
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
