FROM python:3.10

RUN apt update && apt install -y build-essential libffi-dev libfuzzy-dev postgresql-client libmagic1

RUN pip install mwdb-core==2.8.2 karton-core==5.0.0

COPY docker/uwsgi.ini docker/start.sh /app/

WORKDIR /app

CMD ["/app/start.sh"]
