FROM python:3.6

COPY karton-mwdb-reporter/ /tmp/karton-mwdb-reporter
RUN pip install /tmp/karton-mwdb-reporter

COPY karton/ /tmp/karton/
RUN pip install /tmp/karton/

WORKDIR /app
COPY docker/karton.ini /app/karton.ini

CMD karton-mwdb-reporter
