FROM python:3.8

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt install -y nodejs
RUN apt update && apt install -y build-essential libffi-dev libfuzzy-dev postgresql-client libmagic1

COPY mwdb-core/ /tmp/mwdb-core/
RUN pip install /tmp/mwdb-core/

COPY mwdb-plugin-karton/ /tmp/mwdb-plugin-karton/
RUN pip install /tmp/mwdb-plugin-karton/

COPY docker/mwdb.ini docker/uwsgi.ini docker/start.sh docker/karton.ini /app/

WORKDIR /app
# Make fresh web build including plugins
RUN mwdb-core configure web
CMD ["/app/start.sh"]
